### ISSUE TITLE
no MPD after update to 19

### ISSUE THREAD

**Issue by JenKD** [forslund/mpd_skill#13]

**Comment by JenKD** [comment]
Hi, 
after Mycroft update to version 19.02 i noticed that mpd  skilll is not working any more : 

I'm on a debian-testing desktop, mpd is up and running ok.

Mycroft understands what I'm saying :
10:55:20.199 - mycroft.client.speech.listener:transcribe:164 - DEBUG - STT: play
 bob dylan
10:55:20.199 - __main__:handle_utterance:62 - INFO - Utterance: ['play bob dylan
']

but
playback control skill is taking over and Mycroft does not know how to play it 

11:12:54.161 - Playback Control Skill - INFO - Resolving Player for: bob dylan
11:12:54.488 - Playback Control Skill - DEBUG - CommonPlay Resolution: bob dylan
11:12:54.488 - Playback Control Skill - INFO -    No matches

"Give me a moment to check for that 
Sorry, I don't know how to play bob dylan"

Would appreciate it a lot if you could have this fixed !
Thanks and best regards,

Johan

**Comment by forslund** [comment]
Hi @JenKD,

I've pushed a quick fix migrating from the old `emitter` to the current `bus` for messagebus communications. Let me know if this makes it work for you.

/Åke

**Comment by JenKD** [comment]
wow, that's quick! 
it's working.

Thanks !!

**Comment by forslund** [comment]
Ok good to hear, closing this issue now.
