### ISSUE TITLE
No longer working 

### ISSUE THREAD

**Issue by chowbok** [forslund/mpd_skill#2]
This skill does not seem to work at all currently. Would really like to see it fixed as this is the biggest reason I'd like to use Mycroft over Alexa & similar.

**Comment by forslund** [comment]
Hi @chowbok I've just pushed an update that should get basic functionality back into working order.

Still on my todo list:
- Fuzzy matching (currently very picky)
- Padatious intents
- setup mpd-server on home.mycroft.ai instead of through configuration

**Comment by chowbok** [comment]
Works great! I'm sure I'll come across some specific concerns as I use this, but I'm very pleased. Thanks again.
